#https://www.shadertoy.com/view/Xds3Rr

[microphone]
microphone = true

[[pass]]
clear     = [0.0, 0.0, 0.0, 1.0]
draw      = {mode = "triangles", count = 1}
vertex    = "../share/fullscreen_triangle.glsl"
fragment  = "./frag.glsl"
iChannel0 = {resource="microphone", filter="linear", wrap="clamp"}
