#https://www.shadertoy.com/view/lsKGWV

[[pass]]
clear     = [0.0, 0.0, 0.0, 1.0]
draw      = {mode = "triangles", count = 1}
vertex    = "../share/fullscreen_triangle.glsl"
fragment  = "./image.glsl"
